import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const page = await readFile(new URL('../pages/AdminUsersPage.jsx', import.meta.url), 'utf8')
const endpoint = await readFile(new URL('../../supabase/functions/admin-accounts/index.ts', import.meta.url), 'utf8')
const recoveryEndpoint = await readFile(new URL('../../supabase/functions/admin-accounts/recovery.ts', import.meta.url), 'utf8')
const permissions = await readFile(new URL('../config/permissions.js', import.meta.url), 'utf8')
const pagePermissions = await readFile(new URL('../config/adminPagePermissions.js', import.meta.url), 'utf8')
const topbar = await readFile(new URL('../components/AdminTopbar.jsx', import.meta.url), 'utf8')
const migration = await readFile(new URL('../../supabase/migrations/20260829012000_account_presence_and_role_delegation.sql', import.meta.url), 'utf8')
const presenceSplitMigration = await readFile(new URL('../../supabase/migrations/20260830090000_split_presence_counts_and_lists.sql', import.meta.url), 'utf8')
const boundedMigration = await readFile(new URL('../../supabase/migrations/20260829101500_bounded_recovery_backend_accounts.sql', import.meta.url), 'utf8')

test('backend account list returns a privacy-projected creator label and creation timestamp', () => {
  assert.match(endpoint, /must_change_password,account_created_by,created_at/)
  assert.match(endpoint, /const \{ account_created_by: _privateCreatorId, \.\.\.publicAccount \} = x/)
  assert.match(endpoint, /account_created_by_label: accountCreatorLabel\(x\)/)
  assert.match(endpoint, /creatorIsVisible[\s\S]+其他授权管理员/)
  assert.match(endpoint, /if \(!creatorId\) return '系统 \/ 历史导入'/)
  assert.match(page, /创建人[\s\S]+创建时间/)
  assert.match(page, /a\.account_created_by_label[\s\S]+accountDateTime\(a\.created_at\)/)
  assert.doesNotMatch(page, /a\.account_created_by\b/)
  assert.match(boundedMigration, /'created_at', page_row\.created_at/)
  assert.match(boundedMigration, /'account_created_by_label',[\s\S]+其他授权管理员/)
  assert.doesNotMatch(boundedMigration, /'account_created_by', page_row\.account_created_by/)
})

test('account search separates login identity, employee identity and role/scope context', () => {
  for (const key of ['account', 'employee', 'context']) assert.match(page, new RegExp(`${key}:''`))
  assert.match(page, /输入后台用户名/)
  assert.match(page, /输入员工ID或姓名/)
  assert.match(page, /输入角色、管理范围或创建人/)
  assert.match(page, /matchesAccessField\('account', a\.login_username\)/)
  assert.match(page, /matchesAccessField\('employee', a\.employee\?\.employee_no, a\.employee\?\.full_name\)/)
  assert.match(page, /matchesAccessField\('context', role\?\.name, role\?\.code, scopeLabel\(a\.data_scope\), a\.account_created_by_label\)/)
  assert.match(recoveryEndpoint, /new Set\(\['username', 'employee', 'context'\]\)/)
  assert.match(page, /search:\{[\s\S]+username:String\(search\?\.account/)
})

test('online lists require one explicit permission while counts require a valid backend session', () => {
  assert.match(permissions, /ACCOUNT_ONLINE_PRESENCE_VIEW: 'account\.online_presence\.view'/)
  assert.match(pagePermissions, /backend_accounts:[\s\S]+PERMISSIONS\.ACCOUNT_ONLINE_PRESENCE_VIEW/)
  assert.match(topbar, /permissions\?\.includes\(PERMISSIONS\.ACCOUNT_ONLINE_PRESENCE_VIEW\)/)
  assert.match(endpoint, /if \(!can\('account\.online_presence\.view'\)\)/)
  assert.match(recoveryEndpoint, /if \(!can\('account\.online_presence\.view'\)\)/)
  assert.match(recoveryEndpoint, /userClient\.rpc\('admin_online_presence_counts_allowed'\)/)
  assert.match(topbar, /const canPresenceCounts = enabled/)
  assert.match(topbar, /const canPresenceRows = Boolean\([\s\S]+PERMISSIONS\.ACCOUNT_ONLINE_PRESENCE_VIEW/)
  assert.match(migration, /insert into public\.permissions[\s\S]+'account\.online_presence\.view'[\s\S]+true/)
  assert.match(migration, /return public\.has_permission\('account\.online_presence\.view'\)/)
  assert.doesNotMatch(migration, /insert into public\.role_permissions/)
  assert.match(migration, /revoke all on function public\.admin_online_presence_allowed\(\)[\s\S]+from public, anon, authenticated, service_role/)
  assert.match(presenceSplitMigration, /set name = '查看后台与员工在线名单'/)
  assert.match(presenceSplitMigration, /select public\.admin_access_session_allowed\(\)/)
  assert.match(presenceSplitMigration, /It does not authorise online identity rows/)
})

test('supervisor role creation uses a server-only allowlist without relaxing custom or elevated accounts', () => {
  assert.match(migration, /create table if not exists public\.backend_role_assignment_rules/)
  assert.match(migration, /alter table public\.backend_role_assignment_rules enable row level security/)
  assert.match(migration, /revoke all on table public\.backend_role_assignment_rules[\s\S]+from public, anon, authenticated/)
  assert.match(migration, /grant select on table public\.backend_role_assignment_rules[\s\S]+to service_role/)
  assert.match(migration, /grantor\.code = 'supervisor'/)
  for (const code of ['senior_team_leader', 'team_leader', 'trainer', 'assistant']) assert.ok(migration.includes(`'${code}'`))
  assert.match(endpoint, /from\('backend_role_assignment_rules'\)[\s\S]+\.eq\('grantor_role_id', caller\.role_id\)[\s\S]+\.eq\('active', true\)/)
  assert.match(endpoint, /A role-level delegation never covers an account that Founder elevated/)
  assert.match(endpoint, /assignable_role_ids: assignableRoleIds/)
  assert.match(page, /const assignableRoleIds = new Set\(data\?\.assignable_role_ids \|\| \[\]\)/)
  assert.match(page, /accountModal\?\.mode === 'create' \? creationRoles : editableRoles/)
  assert.match(recoveryEndpoint, /from\('backend_role_assignment_rules'\)[\s\S]+\.eq\('active', true\)/)
  assert.match(recoveryEndpoint, /const explicitlyDelegable = new Set/)
  assert.match(boundedMigration, /account_effective_permissions as materialized/)
  assert.match(boundedMigration, /target_permission\.permission_id = any\(v_actor_permission_ids\)/)
  assert.match(boundedMigration, /backend_role_assignment_rules assignment[\s\S]+base_permission\.role_id = access\.role_id/)
})

test('recovery restores bounded Founder permission saves without reopening role lifecycle mutations', () => {
  assert.match(recoveryEndpoint, /action === 'role_list'/)
  assert.match(recoveryEndpoint, /if \(!can\('role\.view'\)\)/)
  assert.match(recoveryEndpoint, /recovery_role_mode:true/)
  assert.match(recoveryEndpoint, /role_permissions_writable:isFounder/)
  assert.match(recoveryEndpoint, /action === 'save_role_permissions'/)
  assert.match(page, /fetchRecoveryRoles\(\)/)
  assert.match(page, /roleReadOnly = !canSaveRolePermissions \|\| roleIsLocked/)
  assert.match(page, /!recoveryRoleMode&&!role\.system_locked/)
})
