import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import test from 'node:test'

import {isCurrentLiveRequest,staleSnapshotNotice} from './requestConsistency.js'

const examMigration=await readFile(new URL('../../supabase/migrations/20260828052000_exam_overview_single_rpc.sql',import.meta.url),'utf8')
const connectivityMigration=await readFile(new URL('../../supabase/migrations/20260828053000_connectivity_home_set_scope.sql',import.meta.url),'utf8')
const trainingPage=await readFile(new URL('../pages/AdminTrainingPage.jsx',import.meta.url),'utf8')
const connectivityPage=await readFile(new URL('../components/ConnectivityRecords.jsx',import.meta.url),'utf8')

const occurrences=(value,pattern)=>value.match(pattern)?.length||0
const between=(value,start,end)=>value.slice(value.indexOf(start),end?value.indexOf(end):value.length)
const examHome=between(examMigration,'create or replace function public.admin_exam_overview_home()','create or replace function public.admin_exam_overview_analytics_summary()')
const examSummary=between(examMigration,'create or replace function public.admin_exam_overview_analytics_summary()','create or replace function public.admin_exam_overview_analytics_dimensions()')
const examDimensions=between(examMigration,'create or replace function public.admin_exam_overview_analytics_dimensions()','create or replace function public.admin_exam_overview_analytics_activity()')
const examActivity=between(examMigration,'create or replace function public.admin_exam_overview_analytics_activity()','create or replace function public.admin_exam_overview_analytics_leaderboard()')
const examLeaderboard=between(examMigration,'create or replace function public.admin_exam_overview_analytics_leaderboard()','notify pgrst')

test('exam overview splits first paint from four bounded analytics RPCs behind one private scope gate',()=>{
  for(const rpc of ['admin_exam_overview_home','admin_exam_overview_analytics_summary','admin_exam_overview_analytics_dimensions','admin_exam_overview_analytics_activity','admin_exam_overview_analytics_leaderboard']){
    assert.match(examMigration,new RegExp(`create or replace function public\\.${rpc}\\(\\)`))
  }
  assert.match(examMigration,/create or replace function exam_private\.admin_exam_overview_scope\(\)/)
  assert.match(examMigration,/revoke all on schema exam_private from public, anon, authenticated, service_role/)
  assert.match(examMigration,/revoke all on function exam_private\.admin_exam_overview_scope\(\)[\s\S]*from public, anon, authenticated, service_role/)
  assert.equal(occurrences(examMigration,/current_app_session_is_valid\('admin'\)/g),1)
  assert.equal(occurrences(examMigration,/has_permission\('exam\.overview\.view'\)/g),1)
  assert.equal(occurrences(examMigration,/admin_scope_effective_employee_ids\(v_user_id\)/g),1)
  assert.equal(occurrences(examMigration,/from exam_private\.admin_exam_overview_scope\(\) scope/g),5)
  assert.match(examMigration,/v_allowed_employee_ids uuid\[\]/)
  assert.match(examMigration,/array_agg\(scope\.employee_id order by scope\.employee_id\)[\s\S]*into v_allowed_employee_ids/)
  assert.match(examMigration,/v_scope_key := pg_catalog\.md5[\s\S]*array_to_string\(v_allowed_employee_ids, ','\)/)
  assert.ok(occurrences(examMigration,/'_scope_key', v_scope_key/g)>=5)

  assert.match(examHome,/current_directory as materialized[\s\S]*scope_private\.current_employee_scope_directory\(\)/)
  assert.match(examHome,/question_scopes as materialized[\s\S]*user_scope_team_filters[\s\S]*user_scope_position_filters/)
  assert.match(examHome,/v_scope = 'assigned_teams' and v_has_position_filters[\s\S]*public\.exam_norm\(position\.name\)[\s\S]*position_key/)
  assert.match(examHome,/scope\.position_key is null[\s\S]*scope\.position_key = public\.exam_norm\(question\.position_name\)/)
  assert.match(examHome,/v_scope = 'own_team'[\s\S]*directory\.employee_id = v_linked_employee_id/)
  assert.match(examHome,/recent_current as materialized[\s\S]*order by session\.started_at desc nulls last[\s\S]*limit 12[\s\S]*answer_counts as materialized/)
  assert.match(examHome,/recent_legacy as materialized[\s\S]*order by session\.started_at desc nulls last[\s\S]*limit 12[\s\S]*answer_counts as materialized/)
  assert.match(examHome,/when session\.graded_by is null then '—'[\s\S]*'后台账号'/)
  assert.equal(occurrences(examHome,/jsonb_array_elements\(/g),2,'only the at-most-24 recent rows may be reparsed from JSON')
  assert.match(examHome,/v_counts_bundle[\s\S]*'current_counts'[\s\S]*'legacy_counts'/)
  assert.doesNotMatch(examHome,/current_answer_totals|session_dimensions|activity_facts|leaderboard_facts|'analytics'/)

  assert.match(examSummary,/current_answer_totals as materialized[\s\S]*legacy_answer_totals as materialized[\s\S]*'summary'[\s\S]*'score_bands'[\s\S]*'sources'/)
  assert.match(examSummary,/'answer_stats_scope', 'synced_detail'[\s\S]*'legacy_answer_count'[\s\S]*'legacy_zero_score_count'/)
  assert.match(examDimensions,/session_dimensions as materialized[\s\S]*cross join lateral \(values[\s\S]*'series'[\s\S]*'positions'[\s\S]*'teams'/)
  assert.equal(occurrences(examDimensions,/and session\.status = 'graded'/g),2)
  assert.match(examActivity,/activity_facts as materialized[\s\S]*days as materialized[\s\S]*'trend'[\s\S]*'daily_activity'/)
  assert.equal(occurrences(examActivity,/and session\.submitted_at >= current_date - interval '29 days'/g),2)
  assert.match(examLeaderboard,/leaderboard_facts as materialized[\s\S]*'leaderboard'/)
  assert.equal(occurrences(examLeaderboard,/and session\.status = 'graded'/g),2)
  assert.doesNotMatch(examMigration,/v_sessions\b|v_current_sessions|v_legacy_sessions/)
  assert.doesNotMatch(examMigration,/scoped_sessions as materialized|cross join analytics_summary/)
  assert.doesNotMatch(examMigration,/exam_employee_in_scope|can_manage_employee/)
  assert.doesNotMatch(examMigration,/grader\.login_email|access\.login_email/)
  assert.match(examMigration,/grader_names as materialized[\s\S]*strpos\(btrim\(access\.login_username\), '@'\) = 0/)
  assert.match(examMigration,/set jit = 'off'/)
})

test('exam overview UI sequences validated analytics, retries transient modules once, and keeps successful modules visible',()=>{
  assert.equal(occurrences(trainingPage,/invokeOverviewRpc\('admin_exam_overview_home'\)/g),1)
  for(const rpc of ['admin_exam_overview_analytics_summary','admin_exam_overview_analytics_dimensions','admin_exam_overview_analytics_activity','admin_exam_overview_analytics_leaderboard'])assert.equal(occurrences(trainingPage,new RegExp(`'${rpc}'`,'g')),1)
  assert.doesNotMatch(trainingPage,/Promise\.all/)
  assert.match(trainingPage,/for\(const \[rpcName,moduleKey,moduleLabel,requiredKeys\] of overviewAnalyticsRpcs\)[\s\S]*await invokeOverviewAnalyticsRpc\(rpcName\)/)
  assert.match(trainingPage,/OVERVIEW_RPC_TIMEOUT_MS=8000[\s\S]*abortSignal\(controller\.signal\)/)
  assert.match(trainingPage,/OVERVIEW_ANALYTICS_RETRY_DELAY_MS=250/)
  assert.match(trainingPage,/retryableOverviewAnalyticsFailure[\s\S]*57014[\s\S]*statement timeout/)
  assert.match(trainingPage,/const invokeOverviewAnalyticsRpc=async rpcName=>[\s\S]*for\(let attempt=0;attempt<2;attempt\+=1\)[\s\S]*latestResponse=await invokeOverviewRpc\(rpcName\)/)
  assert.match(trainingPage,/if\(!overviewRequestActive\(\)\)return \{_cancelled:true,data:null,error:null\}[\s\S]*OVERVIEW_ANALYTICS_RETRY_DELAY_MS/)
  assert.match(trainingPage,/overviewAbortRef\.current\?\.abort\(\)/)
  assert.match(trainingPage,/const overviewFlight=useRef\(null\)/)
  assert.match(trainingPage,/if\(overviewFlight\.current\?\.scopeKey===overviewScopeKey\)return overviewFlight\.current\.promise/)
  assert.match(trainingPage,/overviewHasSnapshot=overviewSnapshot\.scopeKey===overviewScopeKey&&overviewSnapshot\.hasData/)
  assert.match(trainingPage,/overviewData=overviewHasSnapshot\?overviewSnapshot\.data:null/)
  assert.match(trainingPage,/authIdentity\|\|''[\s\S]*access\.permissionKey[\s\S]*access\.dataScope/)
  assert.match(trainingPage,/overviewScopeKeyRef\.current!==requestScopeKey\)return/)
  assert.match(trainingPage,/isCurrentLiveRequest\(aliveRef\.current,overviewRequestRef\.current,requestToken\)/)
  assert.match(trainingPage,/validOverviewHome\(result\)/)
  assert.match(trainingPage,/validOverviewAnalytics\(analyticsPart,requiredKeys\)/)
  assert.match(trainingPage,/prior\.data\?\._scope_key===serverScopeKey/)
  assert.match(trainingPage,/analyticsPart\._scope_key!==serverScopeKey[\s\S]*invalidateOverview\(\)/)
  assert.match(trainingPage,/if\(!publish\(\)\)return[\s\S]*for\(const \[rpcName,moduleKey,moduleLabel,requiredKeys\]/)
  assert.match(trainingPage,/tabRef\.current!=='考试概览'/)
  assert.match(trainingPage,/_analytics_loaded_modules:\[\.\.\.loadedAnalyticsModules\]/)
  assert.match(trainingPage,/_analytics_failed_modules:\[\.\.\.failedAnalyticsModules\.values\(\)\]/)
  assert.match(trainingPage,/_analytics_ready:loadedAnalyticsModules\.size>0/)
  assert.match(trainingPage,/暂时无法更新：\$\{failedModuleLabels\.join\('、'\)\}[\s\S]*其他成功分析正常显示/)
  assert.match(trainingPage,/activityReady\?<div className="exam-daily-strip"/)
  assert.match(trainingPage,/summaryReady&&<div className="exam-analytics-facts"/)
  assert.match(trainingPage,/dimensionsReady&&<AnalyticsColumnChart[\s\S]*leaderboardReady&&<Leaderboard/)
  assert.match(trainingPage,/_analytics_ready[\s\S]*正在读取考试分析/)
  assert.match(trainingPage,/tab==='考试概览'&&\(overviewData[\s\S]*\?<Overview/)
  assert.match(trainingPage,/supabase\.rpc\('admin_exam_question_bank_dashboard'/)
})

test('connectivity home reuses one scope set and opens a useful default window',()=>{
  assert.match(connectivityMigration,/employee_connectivity_incident_date_idx/)
  assert.equal(occurrences(connectivityMigration,/admin_scope_effective_employee_ids\(v_user_id\)/g),1)
  assert.match(connectivityMigration,/current_directory as materialized[\s\S]*scope_private\.current_employee_scope_directory\(\)/)
  assert.match(connectivityMigration,/scoped_employees as materialized/)
  assert.match(connectivityMigration,/directory\.employee_id is not null then current_team\.name[\s\S]*else historical_team\.name/)
  assert.match(connectivityMigration,/strpos\(btrim\(access\.login_username\), '@'\) = 0/)
  assert.doesNotMatch(connectivityMigration,/auth\.users|login_email|split_part\(coalesce\(auth_user\.email/)
  assert.doesNotMatch(connectivityMigration,/can_manage_employee/)
  assert.match(connectivityPage,/businessRecentRange\(30\)/)
  assert.match(connectivityPage,/incident_type:'power_outage'/)
  assert.match(connectivityPage,/const requestToken=\+\+loadRequestRef\.current/)
  assert.match(connectivityPage,/isCurrentLiveRequest\(aliveRef\.current,loadRequestRef\.current,requestToken\)/)
  assert.match(connectivityPage,/staleSnapshotNotice\(current\.snapshotLabel\)/)
  assert.match(connectivityPage,/显示上次成功结果|staleSnapshotNotice/)
})

test('connectivity request consistency ignores late responses and labels retained snapshots',()=>{
  assert.equal(isCurrentLiveRequest(true,7,7),true)
  assert.equal(isCurrentLiveRequest(true,8,7),false)
  assert.equal(isCurrentLiveRequest(false,7,7),false)
  assert.match(staleSnapshotNotice('日期 2026-08-01 至 2026-08-28'),/显示上次成功结果/)
  assert.match(staleSnapshotNotice('日期 2026-08-01 至 2026-08-28'),/2026-08-01/)
})
