import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = relative => readFile(new URL(relative, import.meta.url), 'utf8')

test('recovery edge exposes a bounded current-organization scope directory', async () => {
  const edge = await read('../../supabase/functions/admin-accounts/recovery.ts')
  const directoryStart = edge.indexOf("if (action === 'scope_directory')")
  const accountListStart = edge.indexOf("if (action === 'account_list')", directoryStart)
  const directory = edge.slice(directoryStart, accountListStart)

  assert.ok(directoryStart > 0 && accountListStart > directoryStart)
  assert.match(directory, /\(createMode \? can\('account\.create'\) : can\('account\.edit'\)\) \|\| !can\('scope\.manage'\)/)
  assert.match(directory, /recoveryBackendActionAllowed\(targetAuthUserId, 'account\.edit'\)/)
  assert.match(directory, /admin_recovery_account_scope_directory/)
  assert.match(directory, /RECOVERY_SCOPE_TEAM_LIMIT/)
  assert.match(edge, /supported_edit_data_scopes:supportedEditDataScopes/)
  assert.match(edge, /recovery_scope_editor:recoveryScopeEditor/)
})

test('recovery assigned-scope save sends all filters only to the v2 atomic writer', async () => {
  const edge = await read('../../supabase/functions/admin-accounts/recovery.ts')
  const updateStart = edge.indexOf("if (action === 'update_backend')")
  const nextAction = edge.indexOf("if (action === 'toggle_active' || action === 'toggle_otp')", updateStart)
  const update = edge.slice(updateStart, nextAction)

  assert.match(update, /team_ids', 'position_ids', 'employee_ids'/)
  assert.match(update, /hasScopeFilters/)
  assert.match(update, /can\('scope\.manage'\)/)
  assert.match(update, /admin_recovery_update_backend_account_v2/)
  assert.match(update, /p_team_ids:teamIds/)
  assert.match(update, /p_position_ids:positionIds/)
  assert.match(update, /p_employee_ids:employeeIds/)
  assert.match(update, /admin_recovery_update_backend_account'/)
})

test('database recovery editor validates the hard team boundary and stays service-only', async () => {
  const migration = await read('../../supabase/migrations/20260830163000_recovery_backend_assigned_scope_editor.sql')
  const directoryStart = migration.indexOf('create or replace function public.admin_recovery_account_scope_directory')
  const updateStart = migration.indexOf('create or replace function public.admin_recovery_update_backend_account_v2')
  const directory = migration.slice(directoryStart, updateStart)
  const update = migration.slice(updateStart)

  assert.match(directory, /scope_private\.current_employee_scope_directory\(\)/)
  assert.match(directory, /employee\.status = 'active'/)
  assert.match(directory, /permission\.code in \('\*', 'account\.edit'\)/)
  assert.match(directory, /permission\.code in \('\*', 'scope\.manage'\)/)
  assert.match(directory, /v_actor_scope is distinct from 'all'/)
  assert.match(directory, /limit 100/)
  assert.match(directory, /limit 200/)
  assert.match(directory, /revoke all on function public\.admin_recovery_account_scope_directory[\s\S]+from public, anon, authenticated, service_role/)
  assert.match(directory, /grant execute on function public\.admin_recovery_account_scope_directory[\s\S]+to service_role/)

  assert.match(update, /scope_manage_required/)
  assert.match(update, /auth_user_id in \(p_actor_user_id, p_target_user_id\)[\s\S]+order by access\.auth_user_id[\s\S]+for update/)
  assert.match(update, /assigned_scope_requires_team/)
  assert.match(update, /team_filter_not_in_current_roster/)
  assert.match(update, /position_filter_not_in_selected_current_team/)
  assert.match(update, /employee_filter_not_in_selected_current_team/)
  assert.match(update, /public\.admin_save_account_access_scope\(/)
  assert.match(update, /delete from public\.app_session_leases[\s\S]+delete from auth\.sessions/)
  assert.match(update, /insert into public\.audit_logs[\s\S]+backend_account_scope_update/)
  assert.match(update, /revoke all on function public\.admin_recovery_update_backend_account_v2[\s\S]+from public, anon, authenticated, service_role/)
  assert.match(update, /grant execute on function public\.admin_recovery_update_backend_account_v2[\s\S]+to service_role/)
})

test('assigned-scope hotfix stages validated replacement filters before the preserved authority', async () => {
  const migration = await read('../../supabase/migrations/20260902121315_fix_recovery_assigned_scope_save_order.sql')
  const original = await read('../../supabase/migrations/20260830163000_recovery_backend_assigned_scope_editor.sql')
  const wrapperStart = migration.indexOf('create or replace function public.admin_recovery_update_backend_account_v2')
  const wrapper = migration.slice(wrapperStart)
  const stageStart = wrapper.indexOf('v_staged_scope := public.admin_save_account_scope_filters(')
  const authorityStart = wrapper.indexOf('v_saved := scope_private.admin_recovery_update_backend_account_v2_ordering_base(')

  assert.ok(wrapperStart > 0)
  assert.ok(stageStart > 0 && authorityStart > stageStart)
  assert.match(migration, /alter function public\.admin_recovery_update_backend_account_v2[\s\S]+set schema scope_private/)
  assert.match(migration, /rename to admin_recovery_update_backend_account_v2_ordering_base/)
  assert.match(migration, /revoke all on function scope_private\.admin_recovery_update_backend_account_v2_ordering_base[\s\S]+from public, anon, authenticated, service_role/)
  assert.match(wrapper, /p_data_scope = 'assigned_teams'[\s\S]+v_current_scope = 'assigned_teams'/)
  assert.match(wrapper, /v_filters_changed := v_current_team_ids is distinct from v_team_ids[\s\S]+v_current_position_ids is distinct from v_position_ids[\s\S]+v_current_employee_ids is distinct from v_employee_ids/)
  assert.doesNotMatch(wrapper, /insert into public\.user_scope_(?:team|position|employee)_filters/)
  assert.doesNotMatch(wrapper, /delete from public\.user_scope_(?:team|position|employee)_filters/)
  assert.match(wrapper, /delete from public\.app_session_leases[\s\S]+delete from auth\.sessions/)
  assert.match(wrapper, /insert into public\.audit_logs[\s\S]+backend_account_scope_update/)
  assert.match(wrapper, /revoke all on function public\.admin_recovery_update_backend_account_v2[\s\S]+from public, anon, authenticated, service_role/)
  assert.match(wrapper, /grant execute on function public\.admin_recovery_update_backend_account_v2[\s\S]+to service_role/)

  // The moved function is the unchanged v2 hard boundary: it still validates
  // every current-roster filter before invoking the legacy role authority.
  assert.match(original, /team_filter_not_in_current_roster/)
  assert.match(original, /position_filter_not_in_selected_current_team/)
  assert.match(original, /employee_filter_not_in_selected_current_team/)
  assert.match(original, /public\.admin_recovery_update_backend_account\(/)
})

test('Founder compatibility grant unlocks only recovery account edit and scope management', async () => {
  const migration = await read('../../supabase/migrations/20260902120307_fix_founder_recovery_scope_permissions.sql')

  assert.match(migration, /role\.code = 'founder'/)
  assert.match(migration, /permission\.code in \('account\.edit', 'scope\.manage'\)/)
  assert.match(migration, /on conflict \(role_id, permission_id\) do nothing/)
  assert.doesNotMatch(migration, /permission\.code\s*=\s*'\*'/)
  assert.match(migration, /founder_recovery_permission_install_incomplete/)
})

test('recovery account modal loads and searches scope candidates on demand', async () => {
  const page = await read('../pages/AdminUsersPage.jsx')
  const selection = await read('./adminAccountScopeSelection.js')

  assert.match(page, /fetchRecoveryScopeDirectory/)
  assert.match(page, /includeSelection:true/)
  assert.match(page, /includeSelection:false/)
  assert.match(page, /scope_directory_loaded/)
  assert.match(page, /recovery_scope_editor/)
  assert.match(page, /form\.data_scope === 'assigned_teams' && canManageScope/)
  assert.match(page, /team_ids:form\.team_ids/)
  assert.match(page, /position_ids:form\.position_ids/)
  assert.match(page, /employee_ids:form\.employee_ids/)
  assert.match(page, /当前排班标准团队、岗位和员工候选/)
  assert.match(page, /recoveryScopeRequestKey/)
  assert.match(page, /accountModal\?\.scope_request_key === requestKey/)
  assert.match(page, /scope_request_key:requestKey/)
  assert.match(page, /currentRequestKey !== requestKey/)
  assert.match(page, /const positionsComplete = result\?\.truncated\?\.positions !== true/)
  assert.match(page, /position_ids:positionsComplete[\s\S]+validPositionIds\.has\(id\)[\s\S]+current\.form\.position_ids \|\| \[\]/)
  assert.match(page, /const employeesComplete = result\?\.truncated\?\.employees !== true && employeeQuery === ''/)
  assert.match(page, /const retryScopeDirectory = async \(\) =>/)
  assert.match(page, />重新读取<\/button>/)
  assert.doesNotMatch(page, /请关闭后重新打开编辑窗口再试/)
  assert.match(selection, /position\?\.team_ids/)
  assert.match(selection, /some\(teamId => selectedTeamIds\.has\(teamId\)\)/)
})

test('bounded scope directories never silently drop selections outside a truncated or searched page', async () => {
  const page = await read('../pages/AdminUsersPage.jsx')
  const openStart = page.indexOf('const openEdit = (a) =>')
  const retryStart = page.indexOf('const retryScopeDirectory = async () =>', openStart)
  const saveStart = page.indexOf('const saveAccount = async () =>', retryStart)
  const open = page.slice(openStart, retryStart)
  const retry = page.slice(retryStart, saveStart)

  assert.ok(openStart > 0 && retryStart > openStart && saveStart > retryStart)
  assert.match(open, /const positionsComplete = result\?\.truncated\?\.positions !== true/)
  assert.match(open, /positionIds = positionsComplete[\s\S]+validPositionIds\.has\(id\)[\s\S]+selection\.position_ids \|\| \[\]/)
  assert.match(open, /staleTeamIds[\s\S]+!staleTeamIds\.has\(id\)/)
  assert.match(retry, /const employeesComplete = result\?\.truncated\?\.employees !== true && employeeQuery === ''/)
  assert.match(retry, /employeeIds = includeSelection[\s\S]+employeesComplete[\s\S]+modal\.form\?\.employee_ids \|\| \[\]/)
})

test('recovery assigned-scope save refreshes and atomically prunes hidden stale filters', async () => {
  const page = await read('../pages/AdminUsersPage.jsx')
  const saveStart = page.indexOf('const saveAccount = async () =>')
  const nextFunction = page.indexOf('const refreshRecoveryAccountPage', saveStart)
  const save = page.slice(saveStart, nextFunction)

  assert.ok(saveStart > 0 && nextFunction > saveStart)
  assert.match(save, /fetchRecoveryScopeDirectory\(\{[\s\S]+includeSelection:false/)
  assert.match(save, /const validPositionIds = new Set\(nextPositions\.map\(position => position\.id\)\)/)
  assert.match(save, /const positionsComplete = result\?\.truncated\?\.positions !== true/)
  assert.match(save, /position_ids:positionsComplete[\s\S]+validPositionIds\.has\(id\)[\s\S]+form\.position_ids \|\| \[\]/)
  assert.match(save, /employee_ids:employeesComplete[\s\S]+validEmployeeIds\.has\(id\)[\s\S]+form\.employee_ids \|\| \[\]/)
  assert.match(save, /scope_request_key:requestKey/)
  assert.match(save, /await call\(recoveryAccountMode \? \{[\s\S]+position_ids:form\.position_ids/)
})
