import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const pageUrl=new URL('../pages/AdminEmployeesPage.jsx',import.meta.url)
const edgeUrl=new URL('../../supabase/functions/admin-employees/index.ts',import.meta.url)
const connectivityUrl=new URL('../components/ConnectivityRecords.jsx',import.meta.url)

test('employee drawer shows its seeded row while full detail is still loading', async () => {
  const source=await readFile(pageUrl,'utf8')
  const connectivitySource=await readFile(connectivityUrl,'utf8')
  const drawer=source.slice(source.indexOf('export function EmployeeDrawer'),source.indexOf('function EmployeeTrainerReviewPanel'))

  assert.doesNotMatch(source,/getAllErrorSummaryMap/)
  assert.match(source,/withEmployeeDetailTimeout\(invoke\(\{action:'detail'/)
  assert.match(source,/month_error_count:row\.month_error_count/)
  assert.match(drawer,/EmployeeProfileMetrics data=\{visibleProfileSummary\}/)
  assert.match(drawer,/已先显示员工基础资料/)
  assert.match(drawer,/onClick=\{onRetry\}>重新读取/)
  assert.match(source,/employeeDetailPartialError\(detail\)/)
  assert.match(source,/const selectedEmployeeId=text\(selected\.employee\.id\)/)
  assert.match(source,/const detailRequestId=detailRequestRef\.current/)
  assert.match(source,/selectedEmployeeIdRef\.current!==selectedEmployeeId/)
  assert.match(source,/detailRequestRef\.current!==detailRequestId\|\|text\(prev\?\.employee\?\.id\)!==selectedEmployeeId/)
  assert.match(source,/mergeEmployeeDetailRefresh\(prev,d\)/)
  assert.match(source,/setDetailError\(employeeDetailPartialError\(d\)\)/)
  assert.match(connectivitySource,/employeeMetricCountLabel\(data\?\.month_records,'\u7b14'\)/)
  assert.match(connectivitySource,/employeeMetricCountLabel\(data\?\.exam_attempts,'\u6b21'\)/)
  assert.doesNotMatch(connectivitySource,/Number\(data\?\.exam_attempts\|\|0\)/)
  assert.match(drawer,/employee-drawer-tabs/)
  assert.doesNotMatch(drawer,/loading\?<div className="empty-state">读取完整档案/)
})

test('employee detail resolves permission decisions in one bounded batch', async () => {
  const source=await readFile(edgeUrl,'utf8')
  const detailStart=source.indexOf('if (action === "detail")')
  const detail=source.slice(detailStart,source.indexOf('if (action === "history_list")',detailStart))

  assert.match(source,/async function permissionDecisionBatch/)
  assert.match(source,/from\("permissions"\)[\s\S]*?\.in\("code",uniqueCodes\)/)
  assert.match(source,/from\("user_permission_overrides"\)[\s\S]*?\.in\("permission_id",permissionIds\)/)
  assert.match(source,/from\("role_permissions"\)[\s\S]*?\.in\("permission_id",permissionIds\)/)
  assert.match(detail,/permissionDecisionBatch\(service,caller,detailPermissionCodes\)/)
  assert.match(detail,/permissionAllowedFromBatch/)
  assert.match(detail,/partial_errors:partialErrors/)
  assert.match(detail,/!portalResult\.error/)
  assert.doesNotMatch(detail,/permissionAllowed\(service,caller/)
  assert.doesNotMatch(detail,/permissionAllowedFirstDefined\(service,caller/)
})

test('employee teacher reviews keep employee scope and request only the selected server page', async () => {
  const source=await readFile(pageUrl,'utf8')
  const drawerStart=source.indexOf('export function EmployeeDrawer')
  const panelStart=source.indexOf('function EmployeeTrainerReviewPanel',drawerStart)
  const effectStart=source.indexOf("if(!e.id||activeSection!=='trainer_reviews')",drawerStart)
  const drawerReturn=source.indexOf('return <div className="modal-mask detail-mask"',effectStart)
  const effect=source.slice(effectStart,drawerReturn)
  const panel=source.slice(panelStart,source.indexOf('function EmployeeErrorPanel',panelStart))

  assert.equal((effect.match(/supabase\.rpc\('online_training_list'/g)||[]).length,1)
  assert.doesNotMatch(effect,/Promise\.all/)
  assert.match(effect,/p_employee_id:e\.id/)
  assert.match(effect,/p_query:trainerReviewFilters\.query/)
  assert.match(effect,/p_date_from:trainerReviewFilters\.dateFrom\|\|null/)
  assert.match(effect,/p_date_to:trainerReviewFilters\.dateTo\|\|null/)
  assert.match(effect,/p_page:trainerReviewPage/)
  assert.match(effect,/p_page_size:trainerReviewPageSize/)
  assert.match(effect,/page_size:Number\(payload\.page_size\|\|trainerReviewPageSize\)/)
  assert.match(panel,/>日期起</)
  assert.match(panel,/>日期止</)
  assert.match(panel,/>搜索</)
  assert.match(panel,/pageSizeOptions=\{\[20,30,50,100\]\}/)
  assert.match(panel,/total=\{total\}/)
})

test('employee error and exam histories use bounded local date search and page controls', async () => {
  const source=await readFile(pageUrl,'utf8')
  const drawerStart=source.indexOf('export function EmployeeDrawer')
  const errorEffectStart=source.indexOf("activeSection!=='errors'",drawerStart)
  const trainerEffectStart=source.indexOf("activeSection!=='trainer_reviews'",errorEffectStart)
  const errorEffect=source.slice(errorEffectStart,trainerEffectStart)
  const errorPanelStart=source.indexOf('function EmployeeErrorPanel',drawerStart)
  const examPanelStart=source.indexOf('function EmployeeExamPanel',errorPanelStart)
  const errorPanel=source.slice(errorPanelStart,examPanelStart)
  const examPanel=source.slice(examPanelStart,source.indexOf('function EmployeeExamDetailModal',examPanelStart))

  assert.equal((errorEffect.match(/admin_employee_error_history/g)||[]).length,1)
  assert.match(errorEffect,/p_employee_id:e\.id/)
  assert.match(errorEffect,/p_page:1,p_page_size:100/)
  assert.doesNotMatch(errorEffect,/Promise\.all/)
  assert.match(errorPanel,/filterEmployeeErrorHistory\(sourceRows,filters\)/)
  assert.match(errorPanel,/filteredRows\.slice\(\(resolvedPage-1\)\*pageSize,resolvedPage\*pageSize\)/)
  assert.match(errorPanel,/pageSizeOptions=\{EMPLOYEE_HISTORY_PAGE_SIZES\}/)
  assert.match(errorPanel,/日期和搜索仅筛选这批已加载记录/)
  assert.match(examPanel,/filterEmployeeExamHistory\(sourceRows,filters\)/)
  assert.match(examPanel,/filteredRows\.slice\(\(resolvedPage-1\)\*pageSize,resolvedPage\*pageSize\)/)
  assert.match(examPanel,/pageSizeOptions=\{EMPLOYEE_HISTORY_PAGE_SIZES\}/)
  assert.match(examPanel,/日期和搜索仅筛选这批已加载记录/)
  assert.match(source,/const EMPLOYEE_HISTORY_PAGE_SIZES=\[20,30,50,100\]/)
  assert.match(source,/>日期起</)
  assert.match(source,/>日期止</)
  assert.match(source,/>搜索</)
})
