import { PERMISSIONS } from './permissions.js'

// This is the single frontend registry for current admin-page authorization.
// Navigation, route guards and the role editor all consume the same entry, so
// a checkbox can never silently authorize a different child page.
export const ADMIN_PAGE_PERMISSIONS = Object.freeze({
  home: { view:PERMISSIONS.DASHBOARD_VIEW, actions:[] },
  alerts: { view:PERMISSIONS.ALERT_VIEW, actions:[PERMISSIONS.ALERT_PAYOUT_CHANGE_VIEW,PERMISSIONS.ALERT_RESIGNED_ACCOUNT_ACTIVE_VIEW,PERMISSIONS.ALERT_TODAY_MISSING_CLOCK_IN_VIEW,PERMISSIONS.ALERT_TODAY_MISSING_DAILY_REPORT_VIEW,PERMISSIONS.ALERT_LEAVE_ACTIVITY_VIEW,PERMISSIONS.ALERT_LATE_TIMEOUT_FREQUENCY_VIEW,PERMISSIONS.ALERT_CONSECUTIVE_REST_VIEW,PERMISSIONS.ALERT_WEEKLY_ABSENCE_VIEW,PERMISSIONS.ALERT_MONTHLY_LEAVE_VIEW,PERMISSIONS.ALERT_ERROR_SPIKE_VIEW,PERMISSIONS.ALERT_REPEATED_ERROR_VIEW,PERMISSIONS.ALERT_DEDUCTION_FREQUENCY_VIEW,PERMISSIONS.ALERT_EXAM_FAILED_VIEW,PERMISSIONS.ALERT_LOW_WORKLOAD_STREAK_VIEW,PERMISSIONS.ALERT_MARK_READ,PERMISSIONS.ALERT_FOLLOW_UP,PERMISSIONS.ALERT_SYNC_DIAGNOSTICS_VIEW] },

  employee_directory: { view:PERMISSIONS.EMPLOYEE_DIRECTORY_VIEW, actions:[PERMISSIONS.EMPLOYEE_CREATE,PERMISSIONS.EMPLOYEE_EDIT,PERMISSIONS.EMPLOYEE_DIRECTORY_RESIGN,PERMISSIONS.EMPLOYEE_DIRECTORY_REACTIVATE,PERMISSIONS.EMPLOYEE_DIRECTORY_COMPENSATION_VIEW,PERMISSIONS.EMPLOYEE_DIRECTORY_PAYROLL_RECORDS_VIEW,PERMISSIONS.EMPLOYEE_PRIVATE_NOTE_VIEW,PERMISSIONS.EMPLOYEE_PRIVATE_NOTE_MANAGE,PERMISSIONS.EMPLOYEE_DELETE,PERMISSIONS.EMPLOYEE_COMPENSATION_EDIT,PERMISSIONS.EMPLOYEE_DIRECTORY_EXPORT,PERMISSIONS.SENSITIVE_EMPLOYEE_VIEW,PERMISSIONS.SENSITIVE_EMPLOYEE_EDIT] },
  personnel_reconciliation: { view:PERMISSIONS.EMPLOYEE_RECONCILIATION_VIEW, actions:[] },
  people_analysis: { view:PERMISSIONS.EMPLOYEE_ANALYTICS_VIEW, actions:[PERMISSIONS.EMPLOYEE_MANAGEMENT_RISK_VIEW,PERMISSIONS.TEAM_VIEW,PERMISSIONS.TEAM_EDIT] },
  resignations: { view:PERMISSIONS.EMPLOYEE_RESIGNATIONS_VIEW, actions:[PERMISSIONS.EMPLOYEE_RESIGNATIONS_RESIGN,PERMISSIONS.EMPLOYEE_RESIGNATIONS_REACTIVATE] },
  change_history: { view:PERMISSIONS.EMPLOYEE_CHANGE_HISTORY_VIEW, actions:[] },
  connectivity: { view:PERMISSIONS.CONNECTIVITY_VIEW, actions:[PERMISSIONS.CONNECTIVITY_CREATE,PERMISSIONS.CONNECTIVITY_EDIT,PERMISSIONS.CONNECTIVITY_DELETE] },

  report_overview: { view:PERMISSIONS.REPORT_OVERVIEW_VIEW, actions:[PERMISSIONS.REPORT_OVERVIEW_EXPORT] },
  report_people: { view:PERMISSIONS.REPORT_PEOPLE_VIEW, actions:[PERMISSIONS.REPORT_PEOPLE_EXPORT] },
  report_legacy_schedule: { view:PERMISSIONS.REPORT_LEGACY_SCHEDULE_VIEW, actions:[] },
  report_platform: { view:PERMISSIONS.REPORT_PLATFORM_VIEW, actions:[PERMISSIONS.REPORT_PLATFORM_EXPORT] },
  report_statistics: { view:PERMISSIONS.REPORT_STATISTICS_VIEW, actions:[PERMISSIONS.REPORT_STATISTICS_EXPORT] },
  report_errors: { view:PERMISSIONS.REPORT_ERRORS_VIEW, actions:[PERMISSIONS.REPORT_ERRORS_EDIT,PERMISSIONS.REPORT_ERRORS_EXPORT] },

  schedule_roster: { view:PERMISSIONS.SCHEDULE_ROSTER_VIEW, actions:[PERMISSIONS.SCHEDULE_EDIT] },
  attendance_monthly: { view:PERMISSIONS.ATTENDANCE_MONTHLY_VIEW, actions:[PERMISSIONS.ATTENDANCE_MONTHLY_EDIT,PERMISSIONS.ATTENDANCE_MONTHLY_EXPORT] },
  attendance_today: { view:PERMISSIONS.ATTENDANCE_TODAY_VIEW, actions:[PERMISSIONS.ATTENDANCE_TODAY_EDIT] },
  attendance_records: { view:PERMISSIONS.ATTENDANCE_RECORDS_VIEW, actions:[PERMISSIONS.ATTENDANCE_RECORDS_EDIT,PERMISSIONS.ATTENDANCE_RECORDS_EXPORT] },
  attendance_leave: { view:PERMISSIONS.ATTENDANCE_LEAVE_VIEW, actions:[PERMISSIONS.ATTENDANCE_LEAVE_EDIT,PERMISSIONS.ATTENDANCE_LEAVE_APPROVE] },
  adjustments: { view:PERMISSIONS.ADJUSTMENT_PAGE_VIEW, actions:[PERMISSIONS.ADJUSTMENT_BONUS_VIEW,PERMISSIONS.ADJUSTMENT_DEDUCTION_VIEW,PERMISSIONS.ADJUSTMENT_PAGE_CREATE,PERMISSIONS.ADJUSTMENT_PAGE_EDIT,PERMISSIONS.ADJUSTMENT_PAGE_EXPORT] },

  online_training: { view:PERMISSIONS.ONLINE_TRAINING_REPORT_VIEW, actions:[PERMISSIONS.ONLINE_TRAINING_REPORT_SUBMIT,PERMISSIONS.ONLINE_TRAINING_REPORT_REVIEW,PERMISSIONS.ONLINE_TRAINING_REPORT_MANAGE] },
  exam_overview: { view:PERMISSIONS.EXAM_OVERVIEW_VIEW, actions:[] },
  exam_records: { view:PERMISSIONS.EXAM_RECORDS_VIEW, actions:[PERMISSIONS.EXAM_RECORDS_DELETE,PERMISSIONS.EXAM_RECORDS_EXPORT] },
  exam_question_bank: { view:PERMISSIONS.EXAM_QUESTION_BANK_VIEW, actions:[PERMISSIONS.EXAM_QUESTION_BANK_MANAGE,PERMISSIONS.EXAM_QUESTION_BANK_DELETE] },
  exam_grading: { view:PERMISSIONS.EXAM_GRADING_VIEW, actions:[PERMISSIONS.EXAM_GRADING_GRADE] },

  event_tracking: { view:PERMISSIONS.WORK_EVENT_VIEW, actions:[PERMISSIONS.WORK_EVENT_SUBMIT,PERMISSIONS.WORK_EVENT_MANAGE,PERMISSIONS.WORK_EVENT_EDIT] },
  daily_inspection: { view:PERMISSIONS.WORK_DAILY_INSPECTION_VIEW, actions:[PERMISSIONS.WORK_DAILY_INSPECTION_EDIT] },
  quality_inspection: { view:PERMISSIONS.WORK_QUALITY_INSPECTION_VIEW, actions:[PERMISSIONS.WORK_QUALITY_INSPECTION_EDIT] },

  payroll_pending: { view:PERMISSIONS.PAYROLL_PENDING_VIEW, actions:[PERMISSIONS.PAYROLL_PENDING_EDIT,PERMISSIONS.PAYROLL_PENDING_APPROVE,PERMISSIONS.PAYROLL_PENDING_PUBLISH,PERMISSIONS.PAYROLL_PENDING_RULE_EDIT] },
  payroll_published: { view:PERMISSIONS.PAYROLL_PUBLISHED_VIEW, actions:[PERMISSIONS.PAYROLL_PUBLISHED_EXPORT] },
  payroll_history: { view:PERMISSIONS.PAYROLL_IMPORT_HISTORY_VIEW, actions:[PERMISSIONS.PAYROLL_IMPORT_HISTORY_EDIT,PERMISSIONS.PAYROLL_IMPORT_HISTORY_DELETE] },
  payout_history: { view:PERMISSIONS.PAYROLL_CHANGE_HISTORY_VIEW, actions:[PERMISSIONS.PAYROLL_CHANGE_HISTORY_REVIEW,PERMISSIONS.PAYROLL_CHANGE_HISTORY_DELETE,PERMISSIONS.SENSITIVE_PAYMENT_VIEW,PERMISSIONS.SENSITIVE_PAYMENT_EDIT,PERMISSIONS.SENSITIVE_PAYMENT_APPROVE,PERMISSIONS.SENSITIVE_PAYOUT_VIEW,PERMISSIONS.SENSITIVE_PAYOUT_EDIT,PERMISSIONS.SENSITIVE_PAYOUT_APPROVE] },

  assets: { view:PERMISSIONS.ASSET_VIEW, actions:[] },
  staff_accounts: { view:PERMISSIONS.STAFF_ACCOUNT_VIEW, actions:[PERMISSIONS.USER_MANAGE,PERMISSIONS.USER_DISABLE_EMPLOYEE,PERMISSIONS.USER_ACTIVATION_GENERATE,PERMISSIONS.USER_ACCOUNT_CREATE,PERMISSIONS.USER_ACCOUNT_DISABLE,PERMISSIONS.USER_ACCOUNT_DELETE,PERMISSIONS.USER_EMAIL_CHANGE,PERMISSIONS.USER_PASSWORD_RESET,PERMISSIONS.STAFF_ACCOUNT_UNLOCK,PERMISSIONS.STAFF_ACCOUNT_MFA_RESET] },
  backend_accounts: { view:PERMISSIONS.BACKEND_ACCOUNT_VIEW, actions:[PERMISSIONS.ACCOUNT_ONLINE_PRESENCE_VIEW,PERMISSIONS.ACCOUNT_CREATE,PERMISSIONS.ACCOUNT_EDIT,PERMISSIONS.ACCOUNT_DISABLE,PERMISSIONS.ACCOUNT_DELETE,PERMISSIONS.ACCOUNT_RESET_PASSWORD,PERMISSIONS.BACKEND_ACCOUNT_UNLOCK,PERMISSIONS.BACKEND_ACCOUNT_LOCKOUT_POLICY_MANAGE,PERMISSIONS.ACCOUNT_OTP_TOGGLE,PERMISSIONS.BACKEND_ACCOUNT_MFA_RESET,PERMISSIONS.SCOPE_MANAGE] },
  ip_allowlist: { view:PERMISSIONS.ACCOUNT_IP_ALLOWLIST_VIEW, actions:[PERMISSIONS.ACCOUNT_IP_ALLOWLIST_MANAGE] },
  // Role mutations remain Founder-only by design; do not render a checkbox
  // that a non-Founder can select but the server must reject.
  roles: { view:PERMISSIONS.ROLE_VIEW, actions:[PERMISSIONS.ROLE_AUDIT_VIEW] },
  activity_log: { view:PERMISSIONS.ACCOUNT_ACTIVITY_LOG_VIEW, actions:[] },
  manual: { view:PERMISSIONS.ACCOUNT_MANUAL_VIEW, actions:[] },
})

export function adminPageAccess(pagePermission) {
  const entry = ADMIN_PAGE_PERMISSIONS[pagePermission]
  if (!entry) throw new Error(`Unknown admin permission page: ${pagePermission}`)
  return { pagePermission, permissions:[entry.view] }
}

export function adminPagePermissionCodes(pagePermission) {
  const entry = ADMIN_PAGE_PERMISSIONS[pagePermission]
  return entry ? [...new Set([entry.view,...entry.actions])] : []
}
