import React,{useEffect,useState} from 'react'
import {Navigate,Route,Routes} from 'react-router-dom'
import {supabase,configured} from './lib/supabase'
import AdminLoginPage from './pages/AdminLoginPage'
import StaffLoginPage from './pages/StaffLoginPage'
import StaffRegisterPage from './pages/StaffRegisterPage'
import MfaPage from './pages/MfaPage'
import AdminEmployeesPage from './pages/AdminEmployeesPage'
import AdminUsersPage from './pages/AdminUsersPage'
import {AdminHome,StaffHome,ComingSoon} from './pages/PortalPage'
import AppLayout from './components/AppLayout'
function Protected({children,mode}){const[s,setS]=useState({loading:true,session:null,access:null});useEffect(()=>{let m=true;(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){if(m)setS({loading:false,session:null,access:null});return}const{data:access}=await supabase.from('user_access').select('backend_enabled,employee_portal_enabled,active').eq('auth_user_id',session.user.id).single();if(m)setS({loading:false,session,access})})();return()=>{m=false}},[]);if(s.loading)return <div className="center-screen">Loading...</div>;const login=mode==='admin'?'/admin/login':'/staff/login';if(!s.session||!s.access?.active)return <Navigate to={login} replace/>;if(mode==='admin'&&!s.access.backend_enabled)return <Navigate to="/admin/login" replace/>;if(mode==='staff'&&!s.access.employee_portal_enabled)return <Navigate to="/staff/login" replace/>;return children}
export default function App(){if(!configured)return <div className="center-screen"><div className="config-box"><h2>Supabase 尚未连接</h2><p>检查 GitHub Actions Secrets。</p></div></div>;return <Routes><Route path="/" element={<Navigate to="/staff/login" replace/>}/><Route path="/admin/login" element={<AdminLoginPage/>}/><Route path="/staff/login" element={<StaffLoginPage/>}/><Route path="/staff/register" element={<StaffRegisterPage/>}/><Route path="/admin" element={<Protected mode="admin"><AppLayout mode="admin"><AdminHome/></AppLayout></Protected>}/><Route path="/admin/employees" element={<Protected mode="admin"><AppLayout mode="admin"><AdminEmployeesPage/></AppLayout></Protected>}/><Route path="/admin/users" element={<Protected mode="admin"><AppLayout mode="admin"><AdminUsersPage/></AppLayout></Protected>}/><Route path="/staff" element={<Protected mode="staff"><AppLayout mode="staff"><StaffHome/></AppLayout></Protected>}/><Route path="/staff/schedule" element={<Protected mode="staff"><AppLayout mode="staff"><ComingSoon title="我的排班"/></AppLayout></Protected>}/><Route path="/staff/attendance" element={<Protected mode="staff"><AppLayout mode="staff"><ComingSoon title="我的出勤"/></AppLayout></Protected>}/><Route path="/staff/payroll" element={<Protected mode="staff"><AppLayout mode="staff"><ComingSoon title="我的工资"/></AppLayout></Protected>}/><Route path="/staff/exams" element={<Protected mode="staff"><AppLayout mode="staff"><ComingSoon title="我的考试"/></AppLayout></Protected>}/><Route path="/staff/requests" element={<Protected mode="staff"><AppLayout mode="staff"><ComingSoon title="我的申请"/></AppLayout></Protected>}/><Route path="/admin/security/mfa" element={<Protected mode="admin"><AppLayout mode="admin"><MfaPage/></AppLayout></Protected>}/><Route path="/staff/security/mfa" element={<Protected mode="staff"><AppLayout mode="staff"><MfaPage/></AppLayout></Protected>}/><Route path="*" element={<Navigate to="/staff/login" replace/>}/></Routes>}
