-- Reserved migration version.
--
-- The multi-source error mirror depends on tables introduced by
-- 20260823114000_report_query_performance.sql. Its implementation therefore
-- lives in 20260823173000_report_error_multi_source.sql so a fresh database
-- applies the dependency first. This placeholder remains intentionally empty
-- because the same version was used briefly in one deployed environment.
