-- Near-real-time synchronization for the two private August 2026 attendance
-- sheets. The Google reader pushes a complete A:N snapshot to an Edge
-- Function; this migration provides an allowlisted, atomic ingest boundary.
-- March-July sources cannot be selected by this function and remain immutable.

create table if not exists public.attendance_sheet_sync_runs (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique,
  source_id uuid not null references public.attendance_sheet_sources(id) on delete restrict,
  trigger_kind text not null,
  status text not null default 'running',
  snapshot_hash text not null,
  previous_snapshot_hash text,
  read_row_count integer not null default 0,
  raw_record_count integer not null default 0,
  canonical_record_count integer not null default 0,
  mirror_record_count integer not null default 0,
  inserted_count integer not null default 0,
  updated_count integer not null default 0,
  deleted_count integer not null default 0,
  unchanged_count integer not null default 0,
  matched_count integer not null default 0,
  unmatched_count integer not null default 0,
  ambiguous_count integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb,
  result jsonb,
  captured_at timestamptz,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint attendance_sheet_sync_runs_trigger_check
    check (trigger_kind in ('change', 'daily_reconcile', 'manual')),
  constraint attendance_sheet_sync_runs_status_check
    check (status in ('running', 'success', 'unchanged', 'failed')),
  constraint attendance_sheet_sync_runs_hash_check
    check (snapshot_hash ~ '^[0-9a-f]{64}$'),
  constraint attendance_sheet_sync_runs_previous_hash_check
    check (
      previous_snapshot_hash is null
      or previous_snapshot_hash ~ '^[0-9a-f]{64}$'
    ),
  constraint attendance_sheet_sync_runs_counts_check
    check (
      read_row_count >= 0
      and raw_record_count >= 0
      and canonical_record_count >= 0
      and mirror_record_count >= 0
      and inserted_count >= 0
      and updated_count >= 0
      and deleted_count >= 0
      and unchanged_count >= 0
      and matched_count >= 0
      and unmatched_count >= 0
      and ambiguous_count >= 0
    ),
  constraint attendance_sheet_sync_runs_details_object_check
    check (jsonb_typeof(details) = 'object')
);

create table if not exists public.attendance_sheet_sync_changes (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.attendance_sheet_sync_runs(id) on delete restrict,
  source_id uuid not null references public.attendance_sheet_sources(id) on delete restrict,
  operation text not null,
  source_block text not null,
  source_row integer not null,
  source_item_key text not null,
  record_id uuid,
  before_record jsonb,
  after_record jsonb,
  created_at timestamptz not null default now(),
  constraint attendance_sheet_sync_changes_operation_check
    check (operation in ('insert', 'update', 'delete')),
  constraint attendance_sheet_sync_changes_source_row_check
    check (source_row > 0),
  constraint attendance_sheet_sync_changes_before_object_check
    check (before_record is null or jsonb_typeof(before_record) = 'object'),
  constraint attendance_sheet_sync_changes_after_object_check
    check (after_record is null or jsonb_typeof(after_record) = 'object')
);

-- Persistent private staging avoids trusting caller-owned temporary objects in
-- a SECURITY DEFINER function. Rows exist only for the ingest transaction.
create table if not exists attendance_private.attendance_sheet_sync_stage (
  run_id uuid not null references public.attendance_sheet_sync_runs(id) on delete cascade,
  source_id uuid not null references public.attendance_sheet_sources(id) on delete restrict,
  source_block text not null,
  source_row integer not null,
  source_item_key text not null default 'primary',
  kind text not null,
  event_date date,
  event_kind text not null,
  reason text,
  note text,
  amount numeric,
  raw_amount text,
  employee_no_raw text,
  employee_name_raw text,
  employee_status_raw text,
  team_name_raw text,
  position_name_raw text,
  country_raw text,
  platform_raw text,
  manager_raw text,
  raw_values jsonb not null default '{}'::jsonb,
  content_hash text not null,
  is_mirror boolean not null default false,
  source_updated_at timestamptz,
  primary key (run_id, source_block, source_row, source_item_key),
  constraint attendance_sheet_sync_stage_source_row_check check (source_row > 0),
  constraint attendance_sheet_sync_stage_kind_check
    check (kind in ('attendance', 'resignation', 'adjustment')),
  constraint attendance_sheet_sync_stage_hash_check
    check (content_hash ~ '^[0-9a-f]{64}$'),
  constraint attendance_sheet_sync_stage_raw_values_check
    check (jsonb_typeof(raw_values) = 'object')
);

create index if not exists attendance_sheet_sync_runs_source_started_idx
  on public.attendance_sheet_sync_runs (source_id, started_at desc, id desc);
create index if not exists attendance_sheet_sync_runs_status_started_idx
  on public.attendance_sheet_sync_runs (status, started_at desc, id desc);
create index if not exists attendance_sheet_sync_changes_run_idx
  on public.attendance_sheet_sync_changes (run_id, id);
create index if not exists attendance_sheet_sync_changes_record_idx
  on public.attendance_sheet_sync_changes (
    source_id,
    source_block,
    source_row,
    source_item_key,
    id desc
  );
create index if not exists attendance_sheet_sync_stage_source_idx
  on attendance_private.attendance_sheet_sync_stage (
    source_id,
    source_block,
    source_row,
    source_item_key
  );

alter table public.attendance_sheet_sync_runs enable row level security;
alter table public.attendance_sheet_sync_changes enable row level security;
alter table attendance_private.attendance_sheet_sync_stage enable row level security;

revoke all on table public.attendance_sheet_sync_runs from public, anon, authenticated;
revoke all on table public.attendance_sheet_sync_changes from public, anon, authenticated;
revoke all on table attendance_private.attendance_sheet_sync_stage
  from public, anon, authenticated, service_role;
revoke all on sequence public.attendance_sheet_sync_changes_id_seq
  from public, anon, authenticated;

grant select, insert, update, delete on table public.attendance_sheet_sync_runs
  to service_role;
grant select, insert, update, delete on table public.attendance_sheet_sync_changes
  to service_role;
grant usage, select on sequence public.attendance_sheet_sync_changes_id_seq
  to service_role;

drop policy if exists attendance_sheet_sync_runs_no_direct_access
  on public.attendance_sheet_sync_runs;
create policy attendance_sheet_sync_runs_no_direct_access
  on public.attendance_sheet_sync_runs
  for all to anon, authenticated
  using (false) with check (false);

drop policy if exists attendance_sheet_sync_changes_no_direct_access
  on public.attendance_sheet_sync_changes;
create policy attendance_sheet_sync_changes_no_direct_access
  on public.attendance_sheet_sync_changes
  for all to anon, authenticated
  using (false) with check (false);

create or replace function attendance_private.ingest_august_attendance_snapshot(
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request_id uuid;
  v_run_id uuid;
  v_source_id uuid;
  v_source_key text;
  v_spreadsheet_id text;
  v_sheet_gid text;
  v_tab_name text;
  v_trigger_kind text;
  v_snapshot_hash text;
  v_previous_hash text;
  v_last_captured_at timestamptz;
  v_captured_at timestamptz;
  v_read_row_count integer;
  v_payload_row_count integer;
  v_existing_record_count integer := 0;
  v_inserted integer := 0;
  v_updated integer := 0;
  v_deleted integer := 0;
  v_unchanged integer := 0;
  v_raw integer := 0;
  v_canonical integer := 0;
  v_mirrors integer := 0;
  v_matched integer := 0;
  v_unmatched integer := 0;
  v_ambiguous integer := 0;
  v_result jsonb;
  v_existing_result jsonb;
  v_existing_status text;
  v_existing_source_id uuid;
  v_existing_snapshot_hash text;
  v_error text;
  v_allow_large_delete boolean := false;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'invalid_payload';
  end if;
  if octet_length(p_payload::text) > 6291456 then
    raise exception 'payload_too_large';
  end if;

  v_request_id := nullif(btrim(p_payload->>'request_id'), '')::uuid;
  v_source_key := btrim(coalesce(p_payload#>>'{source,source_key}', ''));
  v_spreadsheet_id := btrim(coalesce(p_payload#>>'{source,spreadsheet_id}', ''));
  v_sheet_gid := btrim(coalesce(p_payload#>>'{source,sheet_gid}', ''));
  v_tab_name := coalesce(p_payload#>>'{source,tab_name}', '');
  v_trigger_kind := lower(btrim(coalesce(p_payload->>'trigger_kind', 'change')));
  v_snapshot_hash := lower(btrim(coalesce(p_payload->>'snapshot_hash', '')));
  v_captured_at := coalesce(nullif(p_payload->>'captured_at', '')::timestamptz, now());
  v_read_row_count := coalesce(nullif(p_payload->>'read_row_count', '')::integer, 0);
  v_allow_large_delete := coalesce((p_payload->>'allow_large_delete')::boolean, false);

  if v_request_id is null then raise exception 'request_id_required'; end if;
  if v_trigger_kind not in ('change', 'daily_reconcile', 'manual') then
    raise exception 'invalid_trigger_kind';
  end if;
  if v_snapshot_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid_snapshot_hash';
  end if;
  if v_read_row_count < 0 or v_read_row_count > 5000 then
    raise exception 'invalid_read_row_count';
  end if;
  if coalesce(jsonb_typeof(p_payload->'rows'), 'null') <> 'array' then
    raise exception 'rows_must_be_array';
  end if;
  v_payload_row_count := jsonb_array_length(p_payload->'rows');
  if v_payload_row_count > 10000 then raise exception 'too_many_records'; end if;

  -- This is intentionally a closed allowlist. No March-July source key, sheet,
  -- tab, or gid can pass this boundary.
  if not (
    (
      v_source_key = 'home_2026_08'
      and v_spreadsheet_id = '10H-0oYe-D6v3xRu9vGxatizi4P11J8WYk20s3_XPus8'
      and v_sheet_gid = '2111783822'
      and v_tab_name = '休假填表'
    )
    or
    (
      v_source_key = 'onsite_2026_08'
      and v_spreadsheet_id = '100xfv19w6zD1bdK0MVLd5kdQtOp8obzrBvI8eE2OUZo'
      and v_sheet_gid = '1309516899'
      and v_tab_name = '休假填表'
    )
  ) then
    raise exception 'source_not_allowlisted';
  end if;

  -- Legacy imports stored 32-character MD5 values. They are not comparable to
  -- the live raw-snapshot SHA-256 and must become NULL for the first full run.
  select
    s.id,
    case
      when lower(s.content_hash) ~ '^[0-9a-f]{64}$' then lower(s.content_hash)
    end
  into v_source_id, v_previous_hash
  from public.attendance_sheet_sources s
  where s.source_key = v_source_key
    and s.source_month = '2026-08'
    and s.sheet_id = v_spreadsheet_id
    and s.sheet_gid = v_sheet_gid
    and s.is_active
  limit 1;
  if v_source_id is null then raise exception 'source_not_configured'; end if;

  -- Serialize complete snapshots per source so two triggers can never interleave
  -- their upsert/delete phases.
  perform pg_advisory_xact_lock(hashtextextended('attendance-august-sync:' || v_source_key, 0));

  -- Refresh mutable source state after acquiring the lock. The first source
  -- lookup establishes the allowlisted ID; this one prevents a waiter from
  -- using the previous run's stale hash/capture watermark.
  select
    case
      when lower(s.content_hash) ~ '^[0-9a-f]{64}$' then lower(s.content_hash)
    end,
    nullif(s.metadata#>>'{live_sync,last_captured_at}', '')::timestamptz
  into v_previous_hash, v_last_captured_at
  from public.attendance_sheet_sources s
  where s.id = v_source_id;

  select r.id, r.status, r.result, r.source_id, r.snapshot_hash
  into v_run_id, v_existing_status, v_existing_result,
       v_existing_source_id, v_existing_snapshot_hash
  from public.attendance_sheet_sync_runs r
  where r.request_id = v_request_id;
  if v_run_id is not null then
    if v_existing_source_id <> v_source_id
      or v_existing_snapshot_hash <> v_snapshot_hash then
      raise exception 'request_id_reuse_mismatch';
    end if;
    return coalesce(
      v_existing_result,
      jsonb_build_object(
        'ok', v_existing_status in ('success', 'unchanged'),
        'request_id', v_request_id,
        'run_id', v_run_id,
        'status', v_existing_status,
        'idempotent_replay', true
      )
    ) || jsonb_build_object('idempotent_replay', true);
  end if;

  insert into public.attendance_sheet_sync_runs (
    request_id,
    source_id,
    trigger_kind,
    status,
    snapshot_hash,
    previous_snapshot_hash,
    read_row_count,
    captured_at,
    details
  ) values (
    v_request_id,
    v_source_id,
    v_trigger_kind,
    'running',
    v_snapshot_hash,
    v_previous_hash,
    v_read_row_count,
    v_captured_at,
    jsonb_build_object(
      'source_key', v_source_key,
      'spreadsheet_id', v_spreadsheet_id,
      'sheet_gid', v_sheet_gid,
      'tab_name', v_tab_name,
      'parser_version', coalesce(p_payload->>'parser_version', 'unknown'),
      'parse_warning_count', coalesce((p_payload->>'parse_warning_count')::integer, 0)
    )
  ) returning id into v_run_id;

  -- Complete snapshots are authoritative, so an older delayed request must
  -- never overwrite a newer accepted snapshot. Audit the rejection without
  -- changing source status, counters, content, or records.
  if v_last_captured_at is not null and v_captured_at < v_last_captured_at then
    v_result := jsonb_build_object(
      'ok', false,
      'request_id', v_request_id,
      'run_id', v_run_id,
      'source_key', v_source_key,
      'status', 'failed',
      'error', 'stale_snapshot'
    );
    update public.attendance_sheet_sync_runs
    set
      status = 'failed',
      error_message = 'stale_snapshot',
      result = v_result,
      completed_at = now()
    where id = v_run_id;
    return v_result;
  end if;

  update public.attendance_sheet_sources
  set status = 'running', sync_started_at = now(), error_message = null, updated_at = now()
  where id = v_source_id;

  -- A repeated change notification with an already-applied hash is a cheap
  -- no-op. Daily/manual reconciliation intentionally continues through the
  -- full authoritative comparison even when the hash is unchanged.
  if v_trigger_kind = 'change' and v_previous_hash = v_snapshot_hash then
    v_result := jsonb_build_object(
      'ok', true,
      'request_id', v_request_id,
      'run_id', v_run_id,
      'source_key', v_source_key,
      'status', 'unchanged',
      'snapshot_hash', v_snapshot_hash,
      'inserted', 0,
      'updated', 0,
      'deleted', 0
    );
    update public.attendance_sheet_sync_runs
    set status = 'unchanged', result = v_result, completed_at = now()
    where id = v_run_id;
    update public.attendance_sheet_sources
    set
      status = 'success',
      synced_at = now(),
      error_message = null,
      metadata = metadata || jsonb_build_object(
        'live_sync', coalesce(metadata->'live_sync', '{}'::jsonb) || jsonb_build_object(
          'enabled', true,
          'architecture', 'apps_script_change_push',
          'last_run_id', v_run_id,
          'last_request_id', v_request_id,
          'last_trigger_kind', v_trigger_kind,
          'last_snapshot_hash', v_snapshot_hash,
          'last_captured_at', v_captured_at,
          'last_completed_at', now()
        )
      ),
      updated_at = now()
    where id = v_source_id;
    return v_result;
  end if;

  begin
    insert into attendance_private.attendance_sheet_sync_stage (
      run_id,
      source_id,
      source_block,
      source_row,
      source_item_key,
      kind,
      event_date,
      event_kind,
      reason,
      note,
      amount,
      raw_amount,
      employee_no_raw,
      employee_name_raw,
      employee_status_raw,
      team_name_raw,
      position_name_raw,
      country_raw,
      platform_raw,
      manager_raw,
      raw_values,
      content_hash,
      is_mirror,
      source_updated_at
    )
    select
      v_run_id,
      v_source_id,
      btrim(x.source_block),
      x.source_row,
      coalesce(nullif(btrim(x.source_item_key), ''), 'primary'),
      btrim(x.kind),
      x.event_date,
      btrim(x.event_kind),
      nullif(btrim(x.reason), ''),
      nullif(btrim(x.note), ''),
      x.amount,
      nullif(btrim(x.raw_amount), ''),
      nullif(btrim(x.employee_no_raw), ''),
      nullif(btrim(x.employee_name_raw), ''),
      nullif(btrim(x.employee_status_raw), ''),
      nullif(btrim(x.team_name_raw), ''),
      nullif(btrim(x.position_name_raw), ''),
      nullif(btrim(x.country_raw), ''),
      nullif(btrim(x.platform_raw), ''),
      nullif(btrim(x.manager_raw), ''),
      coalesce(x.raw_values, '{}'::jsonb),
      lower(btrim(x.content_hash)),
      coalesce(x.is_mirror, false),
      v_captured_at
    from jsonb_to_recordset(p_payload->'rows') as x(
      source_block text,
      source_row integer,
      source_item_key text,
      kind text,
      event_date date,
      event_kind text,
      reason text,
      note text,
      amount numeric,
      raw_amount text,
      employee_no_raw text,
      employee_name_raw text,
      employee_status_raw text,
      team_name_raw text,
      position_name_raw text,
      country_raw text,
      platform_raw text,
      manager_raw text,
      raw_values jsonb,
      content_hash text,
      is_mirror boolean,
      source_updated_at timestamptz
    );

    if (select count(*) from attendance_private.attendance_sheet_sync_stage where run_id = v_run_id)
      <> v_payload_row_count then
      raise exception 'staging_count_mismatch';
    end if;

    if exists (
      select 1
      from attendance_private.attendance_sheet_sync_stage x
      where x.run_id = v_run_id
        and (
          x.source_block not in ('attendance', 'resignation', 'adjustment')
          or x.kind <> x.source_block
          or x.event_kind = ''
          or x.employee_name_raw is null
          or (x.event_date is not null and (x.event_date < date '2026-08-01' or x.event_date >= date '2026-10-01'))
          or (x.kind = 'resignation' and x.event_kind <> 'resignation')
          or (x.kind = 'attendance' and x.is_mirror <> (x.event_kind = 'resignation'))
          or (x.kind <> 'attendance' and x.is_mirror)
          or octet_length(coalesce(x.employee_name_raw, '')) > 2000
          or octet_length(coalesce(x.reason, '')) > 20000
          or octet_length(coalesce(x.note, '')) > 40000
          or octet_length(x.raw_values::text) > 100000
        )
    ) then
      raise exception 'invalid_normalized_record';
    end if;

    select count(*) into v_existing_record_count
    from public.employee_attendance_records r
    where r.source_id = v_source_id;

    select count(*) into v_deleted
    from public.employee_attendance_records r
    where r.source_id = v_source_id
      and not exists (
        select 1
        from attendance_private.attendance_sheet_sync_stage x
        where x.run_id = v_run_id
          and x.source_block = r.source_block
          and x.source_row = r.source_row
          and x.source_item_key = r.source_item_key
      );

    -- A malformed/cleared snapshot must not silently erase a source. A true
    -- bulk removal requires a deliberate manual request with an explicit flag.
    if v_existing_record_count > 0 and v_payload_row_count = 0
      and not (v_trigger_kind = 'manual' and v_allow_large_delete) then
      raise exception 'empty_snapshot_requires_manual_override';
    end if;
    if (
      v_deleted > 100
      or v_deleted > ceil(v_existing_record_count * 0.50)::integer
    )
      and not (v_trigger_kind = 'manual' and v_allow_large_delete) then
      raise exception 'large_delete_requires_manual_override';
    end if;

    select
      count(*) filter (where r.id is null),
      count(*) filter (where r.id is not null and r.content_hash is distinct from x.content_hash),
      count(*) filter (where r.id is not null and r.content_hash = x.content_hash)
    into v_inserted, v_updated, v_unchanged
    from attendance_private.attendance_sheet_sync_stage x
    left join public.employee_attendance_records r
      on r.source_id = v_source_id
      and r.source_block = x.source_block
      and r.source_row = x.source_row
      and r.source_item_key = x.source_item_key
    where x.run_id = v_run_id;

    insert into public.attendance_sheet_sync_changes (
      run_id, source_id, operation, source_block, source_row,
      source_item_key, record_id, before_record
    )
    select
      v_run_id, v_source_id, 'update', r.source_block, r.source_row,
      r.source_item_key, r.id, to_jsonb(r)
    from public.employee_attendance_records r
    join attendance_private.attendance_sheet_sync_stage x
      on x.run_id = v_run_id
      and x.source_block = r.source_block
      and x.source_row = r.source_row
      and x.source_item_key = r.source_item_key
    where r.source_id = v_source_id
      and r.content_hash is distinct from x.content_hash;

    insert into public.attendance_sheet_sync_changes (
      run_id, source_id, operation, source_block, source_row,
      source_item_key, record_id, before_record
    )
    select
      v_run_id, v_source_id, 'delete', r.source_block, r.source_row,
      r.source_item_key, r.id, to_jsonb(r)
    from public.employee_attendance_records r
    where r.source_id = v_source_id
      and not exists (
        select 1
        from attendance_private.attendance_sheet_sync_stage x
        where x.run_id = v_run_id
          and x.source_block = r.source_block
          and x.source_row = r.source_row
          and x.source_item_key = r.source_item_key
      );

    insert into public.attendance_sheet_sync_changes (
      run_id, source_id, operation, source_block, source_row,
      source_item_key
    )
    select
      v_run_id, v_source_id, 'insert', x.source_block, x.source_row,
      x.source_item_key
    from attendance_private.attendance_sheet_sync_stage x
    left join public.employee_attendance_records r
      on r.source_id = v_source_id
      and r.source_block = x.source_block
      and r.source_row = x.source_row
      and r.source_item_key = x.source_item_key
    where x.run_id = v_run_id and r.id is null;

    insert into public.employee_attendance_records (
      source_id,
      source_block,
      source_row,
      source_item_key,
      kind,
      event_date,
      event_kind,
      reason,
      note,
      amount,
      raw_amount,
      employee_no_raw,
      employee_name_raw,
      employee_status_raw,
      team_name_raw,
      position_name_raw,
      country_raw,
      platform_raw,
      manager_raw,
      match_status,
      raw_values,
      content_hash,
      is_mirror,
      source_updated_at,
      synced_at
    )
    select
      v_source_id,
      x.source_block,
      x.source_row,
      x.source_item_key,
      x.kind,
      x.event_date,
      x.event_kind,
      x.reason,
      x.note,
      x.amount,
      x.raw_amount,
      x.employee_no_raw,
      x.employee_name_raw,
      x.employee_status_raw,
      x.team_name_raw,
      x.position_name_raw,
      x.country_raw,
      x.platform_raw,
      x.manager_raw,
      'unmatched',
      x.raw_values,
      x.content_hash,
      x.is_mirror,
      x.source_updated_at,
      now()
    from attendance_private.attendance_sheet_sync_stage x
    where x.run_id = v_run_id
    on conflict (source_id, source_block, source_row, source_item_key)
    do update set
      kind = excluded.kind,
      event_date = excluded.event_date,
      event_kind = excluded.event_kind,
      reason = excluded.reason,
      note = excluded.note,
      amount = excluded.amount,
      raw_amount = excluded.raw_amount,
      employee_no_raw = case
        when public.exam_norm(employee_attendance_records.employee_name_raw)
          = public.exam_norm(excluded.employee_name_raw)
          then coalesce(excluded.employee_no_raw, employee_attendance_records.employee_no_raw)
        else excluded.employee_no_raw
      end,
      employee_name_raw = excluded.employee_name_raw,
      employee_status_raw = case
        when public.exam_norm(employee_attendance_records.employee_name_raw)
          = public.exam_norm(excluded.employee_name_raw)
          then coalesce(excluded.employee_status_raw, employee_attendance_records.employee_status_raw)
        else excluded.employee_status_raw
      end,
      team_name_raw = case
        when public.exam_norm(employee_attendance_records.employee_name_raw)
          = public.exam_norm(excluded.employee_name_raw)
          then coalesce(excluded.team_name_raw, employee_attendance_records.team_name_raw)
        else excluded.team_name_raw
      end,
      position_name_raw = case
        when public.exam_norm(employee_attendance_records.employee_name_raw)
          = public.exam_norm(excluded.employee_name_raw)
          then coalesce(excluded.position_name_raw, employee_attendance_records.position_name_raw)
        else excluded.position_name_raw
      end,
      country_raw = case
        when public.exam_norm(employee_attendance_records.employee_name_raw)
          = public.exam_norm(excluded.employee_name_raw)
          then coalesce(excluded.country_raw, employee_attendance_records.country_raw)
        else excluded.country_raw
      end,
      platform_raw = case
        when public.exam_norm(employee_attendance_records.employee_name_raw)
          = public.exam_norm(excluded.employee_name_raw)
          then coalesce(excluded.platform_raw, employee_attendance_records.platform_raw)
        else excluded.platform_raw
      end,
      manager_raw = case
        when public.exam_norm(employee_attendance_records.employee_name_raw)
          = public.exam_norm(excluded.employee_name_raw)
          then coalesce(excluded.manager_raw, employee_attendance_records.manager_raw)
        else excluded.manager_raw
      end,
      employee_id = null,
      match_status = 'unmatched',
      match_method = null,
      matched_at = null,
      raw_values = case
        when public.exam_norm(employee_attendance_records.employee_name_raw)
          = public.exam_norm(excluded.employee_name_raw)
          then employee_attendance_records.raw_values || excluded.raw_values
        else excluded.raw_values
      end,
      content_hash = excluded.content_hash,
      is_mirror = excluded.is_mirror,
      source_updated_at = excluded.source_updated_at,
      synced_at = now(),
      updated_at = now()
    where employee_attendance_records.content_hash is distinct from excluded.content_hash;

    delete from public.employee_attendance_records r
    where r.source_id = v_source_id
      and not exists (
        select 1
        from attendance_private.attendance_sheet_sync_stage x
        where x.run_id = v_run_id
          and x.source_block = r.source_block
          and x.source_row = r.source_row
          and x.source_item_key = r.source_item_key
      );

    -- Match only the just-synchronized August source. This deliberately avoids
    -- touching March-July records or their source counters.
    with employee_id_keys as materialized (
      select
        upper(btrim(e.employee_no)) match_key,
        count(distinct e.id) match_count,
        case when count(distinct e.id) = 1 then min(e.id::text)::uuid end employee_id
      from public.employees e
      where nullif(btrim(e.employee_no), '') is not null
      group by upper(btrim(e.employee_no))
    ),
    employee_name_keys as materialized (
      select
        public.exam_norm(e.full_name) match_key,
        count(distinct e.id) match_count,
        case when count(distinct e.id) = 1 then min(e.id::text)::uuid end employee_id
      from public.employees e
      where nullif(public.exam_norm(e.full_name), '') is not null
      group by public.exam_norm(e.full_name)
    ),
    proposed as materialized (
      select
        r.id,
        case
          when id_match.match_count = 1 then id_match.employee_id
          when coalesce(id_match.match_count, 0) = 0 and name_match.match_count = 1
            then name_match.employee_id
        end employee_id,
        case
          when id_match.match_count = 1 then 'matched'
          when coalesce(id_match.match_count, 0) > 1 then 'ambiguous'
          when name_match.match_count = 1 then 'matched'
          when coalesce(name_match.match_count, 0) > 1 then 'ambiguous'
          else 'unmatched'
        end match_status,
        case
          when id_match.match_count = 1 then 'employee_id_exact'
          when coalesce(id_match.match_count, 0) = 0 and name_match.match_count = 1
            then 'name_unique_exact'
        end match_method
      from public.employee_attendance_records r
      left join employee_id_keys id_match
        on id_match.match_key = upper(btrim(r.employee_no_raw))
      left join employee_name_keys name_match
        on name_match.match_key = public.exam_norm(r.employee_name_raw)
      where r.source_id = v_source_id
    )
    update public.employee_attendance_records r
    set
      employee_id = p.employee_id,
      match_status = p.match_status,
      match_method = p.match_method,
      matched_at = case when p.match_status = 'matched' then now() end,
      updated_at = case
        when (r.employee_id, r.match_status, r.match_method) is distinct from
          (p.employee_id, p.match_status, p.match_method)
          then now()
        else r.updated_at
      end
    from proposed p
    where p.id = r.id
      and (r.employee_id, r.match_status, r.match_method) is distinct from
        (p.employee_id, p.match_status, p.match_method);

    select
      count(*),
      count(*) filter (where not r.is_mirror),
      count(*) filter (where r.is_mirror),
      count(*) filter (where not r.is_mirror and r.match_status = 'matched'),
      count(*) filter (where not r.is_mirror and r.match_status = 'unmatched'),
      count(*) filter (where not r.is_mirror and r.match_status = 'ambiguous')
    into v_raw, v_canonical, v_mirrors, v_matched, v_unmatched, v_ambiguous
    from public.employee_attendance_records r
    where r.source_id = v_source_id;

    update public.attendance_sheet_sync_changes c
    set record_id = r.id, after_record = to_jsonb(r)
    from public.employee_attendance_records r
    where c.run_id = v_run_id
      and c.operation in ('insert', 'update')
      and r.source_id = c.source_id
      and r.source_block = c.source_block
      and r.source_row = c.source_row
      and r.source_item_key = c.source_item_key;

    update public.attendance_sheet_sources s
    set
      status = 'success',
      row_count = v_canonical,
      matched_count = v_matched,
      unmatched_count = v_unmatched,
      ambiguous_count = v_ambiguous,
      skipped_count = v_mirrors,
      error_count = 0,
      content_hash = v_snapshot_hash,
      synced_at = now(),
      error_message = null,
      metadata = s.metadata || jsonb_build_object(
        'raw_event_count', v_raw,
        'canonical_event_count', v_canonical,
        'mirror_count', v_mirrors,
        'live_sync', jsonb_build_object(
          'enabled', true,
          'architecture', 'apps_script_change_push',
          'last_run_id', v_run_id,
          'last_request_id', v_request_id,
          'last_trigger_kind', v_trigger_kind,
          'last_snapshot_hash', v_snapshot_hash,
          'last_captured_at', v_captured_at,
          'last_completed_at', now()
        )
      ),
      updated_at = now()
    where s.id = v_source_id;

    v_result := jsonb_build_object(
      'ok', true,
      'request_id', v_request_id,
      'run_id', v_run_id,
      'source_key', v_source_key,
      'status', 'success',
      'snapshot_hash', v_snapshot_hash,
      'read_rows', v_read_row_count,
      'raw_records', v_raw,
      'canonical_records', v_canonical,
      'mirror_records', v_mirrors,
      'inserted', v_inserted,
      'updated', v_updated,
      'deleted', v_deleted,
      'unchanged', v_unchanged,
      'matched', v_matched,
      'unmatched', v_unmatched,
      'ambiguous', v_ambiguous
    );

    update public.attendance_sheet_sync_runs
    set
      status = 'success',
      raw_record_count = v_raw,
      canonical_record_count = v_canonical,
      mirror_record_count = v_mirrors,
      inserted_count = v_inserted,
      updated_count = v_updated,
      deleted_count = v_deleted,
      unchanged_count = v_unchanged,
      matched_count = v_matched,
      unmatched_count = v_unmatched,
      ambiguous_count = v_ambiguous,
      result = v_result,
      completed_at = now()
    where id = v_run_id;

    delete from attendance_private.attendance_sheet_sync_stage where run_id = v_run_id;
    return v_result;
  exception when others then
    v_error := left(sqlerrm, 2000);
    delete from attendance_private.attendance_sheet_sync_stage where run_id = v_run_id;
    v_result := jsonb_build_object(
      'ok', false,
      'request_id', v_request_id,
      'run_id', v_run_id,
      'source_key', v_source_key,
      'status', 'failed',
      'error', 'ingest_failed'
    );
    update public.attendance_sheet_sync_runs
    set status = 'failed', error_message = v_error, result = v_result, completed_at = now()
    where id = v_run_id;
    update public.attendance_sheet_sources
    set status = 'failed', error_count = error_count + 1,
        error_message = v_error, synced_at = now(), updated_at = now()
    where id = v_source_id;
    return v_result;
  end;
end;
$$;

create or replace function public.ingest_august_attendance_snapshot(
  p_payload jsonb
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select attendance_private.ingest_august_attendance_snapshot(p_payload);
$$;

revoke all on function attendance_private.ingest_august_attendance_snapshot(jsonb)
  from public, anon, authenticated;
revoke all on function public.ingest_august_attendance_snapshot(jsonb)
  from public, anon, authenticated;
grant usage on schema attendance_private to service_role;
grant execute on function attendance_private.ingest_august_attendance_snapshot(jsonb)
  to service_role;
grant execute on function public.ingest_august_attendance_snapshot(jsonb)
  to service_role;

comment on table public.attendance_sheet_sync_runs is
  'Private audit of authoritative August attendance snapshot sync attempts.';
comment on table public.attendance_sheet_sync_changes is
  'Service-role-only before/after audit for attendance sync inserts, updates, and deletes.';
comment on function public.ingest_august_attendance_snapshot(jsonb) is
  'Service-role-only atomic ingest for the two allowlisted August 2026 private sheets.';

notify pgrst, 'reload schema';
